name: Sequential Execution

on:
  - push

jobs:
  linux:
    name: ğŸ§ Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Works
        run: "true"

      - name: Fails
        run: "false"

      - name: Works too
        run: "true"
